# -*- coding: utf-8 -*-
"""Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eez2ao16ZGvHj4So55H1NWfva4kLbP08
"""

import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

np.random.seed(0)

points = 500
X = np.linspace(-3, 3, points)
y = np.sin(X) + np.random.uniform(-0.5, 0.5, points)

plt.scatter(X, y)

model = Sequential()
#X value input
model.add(Dense(units=50, activation='sigmoid', input_dim=1 ))
model.add(Dense(30, activation='sigmoid'))
model.add(Dense(1)) #single output
print(model.summary())

adam = Adam(lr=0.01)
model.compile(loss='mse', optimizer=adam)#mean square error
model.fit(X, y, epochs=15)

predictions = model.predict(X)
plt.scatter(X, y)
plt.plot(X, predictions, 'ro')
plt.show()